# Generated by Django 3.2 on 2024-01-21 20:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='blog/default.jpg', force_format=None, keep_meta=False, quality=100, scale=['middle', 'center'], size=[1920, 1080], upload_to='blog/'),
        ),
    ]
